export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';
export const ADD_FAVOURITES = 'ADD_FAVOURITES';

export const REQUEST_COMPANY_INFO_PENDING = 'REQUEST_COMPANY_INFO_PENDING';
export const REQUEST_COMPANY_INFO_SUCCESS = 'REQUEST_COMPANY_INFO_SUCCESS';
export const REQUEST_COMPANY_INFO_FAILED = 'REQUEST_COMPANY_INFO_FAILED';

export const REQUEST_COMPANY_LOGO_PENDING = 'REQUEST_COMPANY_LOGO_PENDING';
export const REQUEST_COMPANY_LOGO_SUCCESS = 'REQUEST_COMPANY_LOGO_SUCCESS';
export const REQUEST_COMPANY_LOGO_FAILED = 'REQUEST_COMPANY_LOGO_FAILED';