export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';
// export const CLICK_COUNTER_BUTTON = 'CLICK_COUNTER_BUTTON';
// export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
// export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
// export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';